version: 2.1
orbs:
  android: circleci/android@2.0
  slack: circleci/slack@4.12.1

jobs:
  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Build Android application
          command: ./gradlew clean assembleDebug
      - slack/notify:
          event: fail
          template: basic_fail_1

  unit-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
#      - checkout
#      - android/restore-gradle-cache
#      - run: ./gradlew testDebugUnitTest
#      - android/save-gradle-cache
#      - store_test_results:
#          path: ./app/build/test-results/testDebugUnitTest
      - run:
          name: Unit tests step
          command: echo "Unit tests"

  lint:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Lint step
          command: echo "Lint"

  deploy-firebase:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run: echo "Deploy to firebase"
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "CI/CD workflow (CircleCI)"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nNew QA build"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Details:*\nNew build (App distribution) available $CIRCLE_SHA1"
                }
              }
              ]
            }

  build-release:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run: echo "Build release apk"

workflows:
  android_workflow:
    jobs:
      - build
      - unit-test
      - lint
      - deploy-firebase:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - build-release:
          requires:
            - build
          filters:
            branches:
              only:
                - /release-.*/