version: 2.1
orbs:
  android: circleci/android@2.0
jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - run: ./gradlew testDebugUnitTest
      - android/save-gradle-cache
      - store_test_results:
          path: ./app/build/test-results/testDebugUnitTest

  lint:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Lint step
          command: echo "Lint"

  build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run:
          name: Build step
          command: echo "Build"

  deploy-firebase:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run: echo "Deploy to firebase"

  build-release:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - run: echo "Build release apk"

workflows:
  build:
    jobs:
      - unit-test
      - lint:
          filters:
            branches:
              only:
                - main

  build-and-distribute:
    jobs:
      - unit-test
      - lint
      - deploy-firebase:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - develop

  build-release-artifact:
    jobs:
      - unit-test
      - lint
      - build-release:
          requires:
            - unit-test
          filters:
            branches:
              only:
                - /release-.*/