name: Android PR workflow

on:
  push:
    branches:
      - main
      - qa
      - develop
      - test-ci
  pull_request:
    branches:
      - develop
      - qa
      - test-ci
jobs:
  test:
    name: Job Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

#  lint:
#    name: Job Lint Check
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Lint debug flavor
#        run: bash ./gradlew lintDebug --stacktrace
#      - name: Lint results
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/reports/lint-results-debug.html
#
#  build:
#      name: Job Build
#      runs-on: ubuntu-latest
##      if: github.ref == 'refs/heads/test-ci'
#      steps:
#        - uses: actions/checkout@v3
#        - name: set up JDK 11
#          uses: actions/setup-java@v3
#          with:
#            java-version: '11'
#            distribution: 'temurin'
#            cache: gradle
#
#        - name: Grant execute permission for gradlew
#          run: chmod +x gradlew
#        - name: Build with Gradle
#          run: ./gradlew build